# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Naui_config = debug
  NauiApp_config = debug
  UnitTest_config = debug

else ifeq ($(config),release)
  Naui_config = release
  NauiApp_config = release
  UnitTest_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Naui NauiApp UnitTest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Naui:
ifneq (,$(Naui_config))
	@echo "==== Building Naui ($(Naui_config)) ===="
	@${MAKE} --no-print-directory -C . -f Naui.make config=$(Naui_config)
endif

NauiApp: Naui
ifneq (,$(NauiApp_config))
	@echo "==== Building NauiApp ($(NauiApp_config)) ===="
	@${MAKE} --no-print-directory -C . -f NauiApp.make config=$(NauiApp_config)
endif

UnitTest: Naui
ifneq (,$(UnitTest_config))
	@echo "==== Building UnitTest ($(UnitTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f UnitTest.make config=$(UnitTest_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Naui.make clean
	@${MAKE} --no-print-directory -C . -f NauiApp.make clean
	@${MAKE} --no-print-directory -C . -f UnitTest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Naui"
	@echo "   NauiApp"
	@echo "   UnitTest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"